### ISSUE TITLE
Corrupted sb3 won't load after minimizing

### ISSUE THREAD

**Issue by RokCoder** [Xeltalliv/ScratchTools#2]
Running the new minimizer (default options which I believe is all of them) on project# 339207237 (from downloaded file) results in error when loading into TurboWarp (and presumably Scratch) -

`Could not load project: {"validationError":"Could not parse as a valid SB2 or SB3 project.","sb3Errors":[{"keyword":"type","dataPath":".targets[13].blocks['7Jq']","schemaPath":"#/type","params":{"type":"object"},"message":"should be object"},{"keyword":"type","dataPath":".targets[13].blocks['7Jq'][3]","schemaPath":"#/definitions/variable_primitive/additionalItems/type","params":{"type":"number"},"message":"should be number"},{"keyword":"enum","dataPath":".targets[13].blocks['7Jq'][0]","schemaPath":"#/definitions/list_primitive/items/0/enum","params":{"allowedValues":[13]},"message":"should be equal to one of the allowed values"},{"keyword":"oneOf","dataPath":".targets[13].blocks['7Jq']","schemaPath":"#/oneOf","params":{"passingSchemas":null},"message":"should match exactly one schema in oneOf"},{"keyword":"oneOf","dataPath":".targets[13].blocks['7Jq']","schemaPath":"#/properties/blocks/additionalProperties/oneOf","params":{"passingSchemas":null},"message":"should match exactly one schema in oneOf"}],"sb2Errors":[{"keyword":"required","dataPath":"","schemaPath":"#/required","params":{"missingProperty":"objName"},"message":"should have required property 'objName'"}]}`

**Comment by Xeltalliv** [comment]
It should now be fixed

Scratch wiki page on [scratch file format](https://en.scratch-wiki.info/wiki/Scratch_File_Format) has this:
![image](https://github.com/Xeltalliv/ScratchTools/assets/90340988/8c4dcdb0-e714-401b-bc92-36d3b3fcf999)
One of the standalone variable-reading blocks in the project was saved as:
![image](https://github.com/Xeltalliv/ScratchTools/assets/90340988/78787a26-19d3-4587-80ad-31d0cff41e41)
By standalone I mean that is was in listed in `blocks` and had it's own block id. When I coded minimizer I expected all such blocks to have position. This one does not. Interestingly, despite not having position, it's also not connected to any other blocks.
The corruption issue was caused by:
![image](https://github.com/Xeltalliv/ScratchTools/assets/90340988/93199512-359e-4a97-852b-82d0e8a3abc5)
Which was turning it into:
![image](https://github.com/Xeltalliv/ScratchTools/assets/90340988/c58beb97-c254-41b0-b79c-6aff9aa4a88e)

Another bug I've noticed is that here variable id `8}lcQ3ZRzGY;$lcWWZ5%` was not getting shortened. That has also been fixed.
![image](https://github.com/Xeltalliv/ScratchTools/assets/90340988/ddf916fc-a280-4330-b244-ecedb8b56c55)
