### ISSUE TITLE
List2img can't handle single item (joined item?) lists.

### ISSUE THREAD

**Issue by DiamondYoshi** [Xeltalliv/ScratchTools#4]
I made a project that uses Img2list for creating usable images for that project, but someone can't export a list without seeing inside the project, and it's not possible to make a list in 1 line. The idea is that if the user uploads a list that's 1 line long, it would allow them to set a text character to separate the text by, since sometimes lists are stored as a single line of multiple list items.

**Comment by Xeltalliv** [comment]
Considering this isn't going to be a frequently used feature outside of your project and that I want to keep the UI as simple as possible, instead of making it configurable I added 2 predetermined options that get triggered automatically with no extra UI. You can now separate by either commas (all the spaces get removed) or spaces (if there are no commas)

https://github.com/Xeltalliv/ScratchTools/blob/a951268f8b650cad1d654241a4bb113915952cae/List2img/main.js#L48-L50

**Comment by DiamondYoshi** [comment]
Thank you very much!
